language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - python --version
  - cp .travis-perylune.ini perylune.ini

script: make check

notifications:
  email:
    recipients:
      - spam.travis@klub.com.pl
    on_success: change
    on_failure: always
