language: python

python:
  "3.6"
  "3.7"
  "3.8"

before_install:
  - python --version

script: make check

notifications:
  recipients:
    - spam.travis@klub.com.pl
  email:
    on_success: change
    on_failure: always
