language: python

python:
  - "3.7"

before_install:
  - python --version

script: make check

notifications:
  email:
    recipients:
      - spam.travis@klub.com.pl
    on_success: change
    on_failure: always
